name: 'vwx-status'

services:
  web:
    image: pickleshb/vwx_status:latest
    container_name: 'vwx-status'
    ports:
      - "303:300"
    restart: unless-stopped
    env_file:
      - env
    depends_on:
      - db

  db:
    image: ubuntu/postgres:latest
    container_name: 'vwx-status-db'
    restart: unless-stopped
    env_file:
      - env
    volumes:
      - data:/var/lib/postgresql/data

  q-worker:
    image: pickleshb/vwx_status:latest
    container_name: 'vwx-status-worker'
    restart: unless-stopped
    entrypoint: /code/docker/worker_run.sh
    env_file:
      - env
    depends_on:
      - web

volumes:
    # NOTE: Change /path/to/data to a directory on your local machine
    # Persistent data, stored external to the container(s)
    data:
        driver: local
        driver_opts:
            type: none
            o: bind
            # This directory specified where InvenTree data are stored "outside" the docker containers
            # Change this path to a local system path where you want InvenTree data stored
            device: /home/harry/vwx-status/data
