# Generated by Django 3.2.3 on 2021-06-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersettings',
            name='rml_port_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapersettings',
            name='rmt_port_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
