# Generated by Django 3.2.3 on 2021-06-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20210606_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapersettings',
            old_name='rmt_port_2',
            new_name='isv_port',
        ),
        migrations.RenameField(
            model_name='scrapersettings',
            old_name='rml_port_1',
            new_name='rml_port',
        ),
    ]
