# Generated by Django 3.2.3 on 2021-06-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20210607_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapersettings',
            old_name='rml_address',
            new_name='rlm_address',
        ),
        migrations.RenameField(
            model_name='scrapersettings',
            old_name='rml_port',
            new_name='rlm_port',
        ),
    ]
