# Generated by Django 3.2.3 on 2021-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20210609_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uptimehistory',
            options={'verbose_name_plural': 'Uptime history'},
        ),
        migrations.RemoveField(
            model_name='uptimetest',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='uptimetest',
            name='hostname',
            field=models.CharField(default='', help_text='IP address for internal tests and hostname for external tests', max_length=50),
            preserve_default=False,
        ),
    ]
