# Generated by Django 3.2.3 on 2021-06-10 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20210609_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimehistory',
            name='test_ran_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
