# Generated by Django 3.2.3 on 2021-06-11 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_rlminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rlminfo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 11, 1, 12, 843368, tzinfo=utc)),
        ),
    ]
