# Generated by Django 3.2.3 on 2021-06-11 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_alter_rlminfo_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rlminfo',
            options={'verbose_name': 'RLM info', 'verbose_name_plural': 'RLM info'},
        ),
        migrations.AlterModelOptions(
            name='scrapersettings',
            options={'verbose_name_plural': 'Scraper settings'},
        ),
        migrations.AlterField(
            model_name='rlminfo',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
