# Generated by Django 3.2.3 on 2021-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20210611_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
    ]
