# Generated by Django 3.2.3 on 2021-06-17 14:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0011_maintenanceperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 17, 7, 52, 536253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
