# Generated by Django 3.2.24 on 2024-04-04 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_auto_20210617_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 2, 45, 9, 698585, tzinfo=utc)),
        ),
    ]
