# Generated by Django 3.2.24 on 2024-04-04 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_alter_maintenanceperiod_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicenseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('checkout_stamp', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Licence Usage',
                'verbose_name_plural': 'License Usages',
            },
        ),
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 2, 46, 43, 887180, tzinfo=utc)),
        ),
    ]
